language: python
python:
  - 3.6

script:
  - make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _build/html
  on:
    branch: master